### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Tokuriku** [jgpippin/sldb#2]
As it stands, it is impossible to create the table on the SQL database because the "index" file demands that any access to the page be authenticated. Since the password is passed through a special format address in the URL, even going to the page with a browser with the method "Install" does not work.

I personally commented the authentication request out to install and then uncommented it to have it work.

**Comment by Tokuriku** [comment]
I see this is fixed in the JSON branch

**Comment by jgpippin** [comment]
The JSON branch isn't ready though; I still have to rewrite the example.lsl script to parse the JSON.  This is a good catch, and I'm appalled that it's been permitted to exist.  I don't see how anybody has been able to install without doing exactly what you did.

**Comment by jgpippin** [comment]
Quick hotfix to remove this conflict.  I haven't had time to test.

A note on the JSON branch - this branch is intended to do this a bit more "properly," using HTTP codes for authentication errors and a JSON response for use with the introduced llJson\* features in LSL.  I'm working on it a bit slowly, but it should be a more powerful implementation when it's complete in a couple of weeks.
