### ISSUE TITLE
Issue: Attempting to Read Data From DB

### ISSUE THREAD

**Issue by Marc123Shoreland** [jgpippin/sldb#3]
Ok so i am having an issue trying to use the example script in order to LLOwnerSay(name); where it would get the name field from the db. There is no errors , and the variable name has nothing assigned to it. Thanks for any help!

**Comment by Tokuriku** [comment]
Can you get a look in your database to see if the name is there under the right UUID key.

**Comment by ghost** [comment]
The uuid field has 32 characters change this to 36

**Comment by jgpippin** [comment]
Ah, whoops. Solid point. In a previous version I was sanitizing the key by removing dashes for some reason; I got rid of that in this update but failed to update the size of the key field.
